import Header from '@/components/Header'
import './globals.css'
import Footer from '@/components/Footer'
import Head from 'next/head'




export const metadata = {
  title: 'Online Shoe Store',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body >
      <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  )
}
